In [4]:
import pandas as pd
dataFile='.\\Data\\titanic.csv'

In [5]:
data=pd.read_csv(dataFile)

In [6]:
data.head()


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

# Classifying Survivals based on Pclass,Sex,Age,Fare

In [47]:
inputs=data[['Pclass','Sex','Age','Fare']]
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

C:\Users\bipin\AppData\Local\Temp\ipykernel_6432\3644983317.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inputs.Age = inputs.Age.fillna(inputs.Age.mean())


Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [48]:
inputs.Age[:10]

0    22.000000
1    38.000000
2    26.000000
3    35.000000
4    35.000000
5    29.699118
6    54.000000
7     2.000000
8    27.000000
9    14.000000
Name: Age, dtype: float64

In [49]:
#Here changing sex from text to number using one hot encoding
dx=pd.get_dummies(inputs.Sex)

In [50]:
dx.head(5)

female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [51]:
inputs.head()

Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [52]:
x_now=pd.concat([inputs,dx],axis='columns')

In [53]:
x_now.head()

Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [54]:
x=x_now.drop(['Sex','male'],axis='columns')

In [55]:
x.head()

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1
3       1  35.0  53.1000       1
4       3  35.0   8.0500       0

In [56]:
y=data.Survived

In [57]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

# Now spliting the datasets into training and testing

In [58]:
from sklearn.model_selection import train_test_split

In [73]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=20)

In [74]:
x_train.shape

(712, 4)

In [75]:
x_test.shape

(179, 4)

# Now creating the Decision Tree Model

In [76]:
from sklearn import tree

model=tree.DecisionTreeClassifier()

In [77]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [78]:
model.score(x_test,y_test)

0.8044692737430168

In [79]:
model.predict(x_test[:5])

array([1, 0, 0, 0, 1], dtype=int64)

In [80]:
y_test[:5].to_numpy()

array([1, 0, 0, 0, 1], dtype=int64)

Here you can clearly see that my model is 80% accurate 

In [81]:
yp=model.predict(x_test)

In [82]:
from sklearn.metrics import confusion_matrix


In [83]:
cm=confusion_matrix(y_test,yp)

In [84]:
print(cm)

[[94 18]
 [17 50]]


Here confusion matrix shows that (94+50) times it predictd the right answer and (18+17) times it predicted the wrong